## ============================================================================
## Filename          : $RCSfile: batch_analyse_terms.r,v $
## Version           : $Revision: 1.2 $
## Release           : $Name:  $
##
## Original author   : Peter Dreisiger, MOD, DSTO Stirling
## Original date     : 3-Mar-2009
## Last modified by  : $Author: prd $
## Last modified on  : $Date: 2009/04/01 06:44:31 $
##
## Security class.   : UNCLASSIFIED
## Copyright         : DSTO
##
## Purpose           : This R function takes the output of batch_read_terms
##                     and calculates the mean and standard deviations of each
##                     terms' errors-squared and delta-Rs.
##
## Parameters        : [results]  an object generated by batch_read_terms
## Returns           : a list consisting of $drsize, $terms, $epochs, $errors.
##                     mean, $errors.sd, $deltaRs.mean and $deltaRs.sd
##
## Revision history  :
## ============================================================================
batch_analyse_terms <- function(results) {
  # Note that [results] is a list that consists of $terms, $representations and 
  # $errors.  dim($terms) == last-first+1, dim($representations) == c(numberOf-
  # Trials, numberOfSteps, last-first+1, drsize), and dim($errors) == c(number-
  # OfTrials, numberOfSteps, last-first+1).

  # Calculate the term means and sds for each step
  write("Calculating per-term error means and standard deviations", file="")
  errors.mean <- array(dim=c(dim(results$errors)[3], dim(results$errors)[2]))
  errors.sd   <- array(dim=c(dim(results$errors)[3], dim(results$errors)[2]))
  for (term in 1:dim(results$errors)[3])
    for (step in 1:dim(results$errors)[2]) {
      errors.mean[term, step] <- mean(as.vector(results$errors[, step, term]))
      errors.sd[term, step]   <-   sd(as.vector(results$errors[, step, term]))
    }

  # Calculate the average delta-Rs for each term and step.  dim(deltaRs) ==
  # c(NumberOfTrials, NumberOfTerms, NumberOfSteps-1)
  write("Computing the per-term delta-r's", file="")
  deltaRs <- array(dim=c(dim(results$representations)[1], dim(results$representations)[3], dim(results$representations)[2]-1))
  for (trial in 1:dim(results$representations)[1])
    for (term in 1:dim(results$representations)[3])
      for (step in 1:(dim(results$representations)[2]-1))
        deltaRs[trial, term, step] <- sqrt(sum((results$representations[trial, step+1, term, ] - results$representations[trial, step, term, ])^2))

  write("Computing the per-term delta-rs' means and standard deviations", file="")
  deltaRs.mean <- array(dim=c(dim(deltaRs)[2], dim(deltaRs)[3]))
  deltaRs.sd   <- array(dim=c(dim(deltaRs)[2], dim(deltaRs)[3]))
  for (term in 1:dim(deltaRs)[2])
    for (step in 1:dim(deltaRs)[3]) {
      deltaRs.mean[term, step] <- mean(as.vector(deltaRs[, term, step]))
      deltaRs.sd[term, step]   <-   sd(as.vector(deltaRs[, term, step]))
    }

  return(list(drsize=results$drsize, terms=results$terms, epochs=results$epochs, 
              errors.mean=errors.mean, errors.sd=errors.sd,
              deltaRs.mean=deltaRs.mean, deltaRs.sd=deltaRs.sd))

  # $RCSfile: batch_analyse_terms.r,v $    $Revision: 1.2 $
}
